version: '2'

services:

  sshd:
    build: .
    environment:
      - 'SSH_USERHASH_ALL=user1:pass1 user2:pass2'
        #    volumes:
        #      - "${PWD}/user1:/home/user1"
        
    ports:
      - "0.0.0.0:2222:22/tcp"

